baseURL = "https://mengattorney.me/"
languageCode = "zh-cn"
title = "鍏荤尗鐨凜C"
theme = "PaperMod"

[params]
  author = "CC"
  description = " "
  images = ["/covers/wechat-cover.jpg"]

  [params.profileMode]
    enabled = true
    title = "鍏荤尗鐨凜C"
    subtitle = " "
    imageUrl = "/covers/site-cover.jpg"
    imageTitle = "鍗氬灏侀潰"
    imageWidth = 220
    imageHeight = 220

  [[params.profileMode.buttons]]
    name = "鎵€鏈夋枃绔?
    url = "/posts/"
