baseURL = "https://mengattorney.me/"
languageCode = "zh-cn"
title = "CC Blog"
theme = "PaperMod"

[params]
  author = "CC"
  description = " "
  images = ["/covers/wechat-cover.jpg"]

  [params.profileMode]
    enabled = true
    title = "CC Blog"
    subtitle = " "
    imageUrl = "/covers/site-cover.jpg"
    imageTitle = "Blog cover"
    imageWidth = 220
    imageHeight = 220

  [[params.profileMode.buttons]]
    name = "All posts"
    url = "/posts/"
