baseURL = "https://mengattorney.me/"
languageCode = "zh-cn"
title = "养猫的CC"
theme = "PaperMod"

[params]
  author = "CC"
  description = " "
  images = ["/covers/site-cover.jpg"]

  [params.profileMode]
    enabled = true
    title = "养猫的CC"
    subtitle = " "
    imageUrl = "/covers/site-cover.jpg"
    imageTitle = "博客封面"
    imageWidth = 220
    imageHeight = 220

  [[params.profileMode.buttons]]
    name = "所有文章"
    url = "/posts/"